### ISSUE TITLE
iOS SDK is not installing

### ISSUE THREAD

**Issue by christophemenager** [phrase/react_native_sdk_example#2]
Thanks a lot for releasing this react-native sdk ! 

I am stuck in the first step of installation : 
1. `yarn add react-native-phrase-sdk` 
2. `cd ios`
3. `pod install`
4. No changes in the Podfile.lock => the ios sdk is not installed

Do you have an idea to help me ? 

Other small question : 
Is `ENVIRONMENT_ID` the name of the environment ("staging" or "production" for example) ?

Does this name has to follow a convention ?

Thanks a lot for your help,

**Comment by christophemenager** [comment]
@DarkMinstrel @theSoenke @egze do you have an idea to solve this issue ? Thanks a lot !

**Comment by egze** [comment]
I'll check about `yarn` and get back to you.

The `ENVIRONMENT_ID` would be either the `Development secret` or `Production Secret` from Phrase.
<img width="587" alt="React Native Aleks Demo · Over the Air · Phrase 2021-11-02 14-03-53" src="https://user-images.githubusercontent.com/29657/139852169-f26cd813-793d-4a16-b273-3e3aadd6f19e.png">

**Comment by egze** [comment]
These are the steps that I did:

1) `git clone git@github.com:phrase/react_native_sdk_example.git `
2) `cd react_native_sdk_example/ios`
3) `gem install cocoapods`
4) `pod install`

Then I got the `Podfile.lock` just fine. Can you repeat the same steps please and report back?

**Comment by christophemenager** [comment]
> I'll check about `yarn` and get back to you.
> 
> The `ENVIRONMENT_ID` would be either the `Development secret` or `Production Secret` from Phrase. <img alt="React Native Aleks Demo · Over the Air · Phrase 2021-11-02 14-03-53" width="587" src="https://user-images.githubusercontent.com/29657/139852169-f26cd813-793d-4a16-b273-3e3aadd6f19e.png">

Thanks for this, very clear !

**Comment by christophemenager** [comment]
> These are the steps that I did:
> 
> 1. `git clone git@github.com:phrase/react_native_sdk_example.git `
> 2. `cd react_native_sdk_example/ios`
> 3. `gem install cocoapods`
> 4. `pod install`
> 
> Then I got the `Podfile.lock` just fine. Can you repeat the same steps please and report back?

What I did : 
1. `git clone git@github.com:phrase/react_native_sdk_example.git `
2. `cd react_native_sdk_example`& `yarn install`(js dependencies has to be installed first)
2. `cd ios`
4. `pod install`

My cocoapod version : 1.11.2

Output of the `pod install `command : 

``` bash
Auto-linking React Native module for target `PhraseSdkExample`: RNCAsyncStorage
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Downloading dependencies
Installing CocoaAsyncSocket (7.6.5)
Installing DoubleConversion (1.1.6)
Installing FBLazyVector (0.65.1)
Installing FBReactNativeSpec (0.65.1)
Installing Flipper (0.93.0)
Installing Flipper-Boost-iOSX (1.76.0.1.11)
Installing Flipper-DoubleConversion (3.1.7)
Installing Flipper-Fmt (7.1.7)
Installing Flipper-Folly (2.6.7)
Installing Flipper-Glog (0.3.6)
Installing Flipper-PeerTalk (0.0.4)
Installing Flipper-RSocket (1.4.3)
Installing FlipperKit (0.93.0)
Installing OpenSSL-Universal (1.1.180)
Installing RCT-Folly (2021.04.26.00)
Installing RCTRequired (0.65.1)
Installing RCTTypeSafety (0.65.1)
Installing RNCAsyncStorage (1.15.9)
Installing React (0.65.1)
Installing React-Core (0.65.1)
Installing React-CoreModules (0.65.1)
Installing React-RCTActionSheet (0.65.1)
Installing React-RCTAnimation (0.65.1)
Installing React-RCTBlob (0.65.1)
Installing React-RCTImage (0.65.1)
Installing React-RCTLinking (0.65.1)
Installing React-RCTNetwork (0.65.1)
Installing React-RCTSettings (0.65.1)
Installing React-RCTText (0.65.1)
Installing React-RCTVibration (0.65.1)
Installing React-callinvoker (0.65.1)
Installing React-cxxreact (0.65.1)
Installing React-jsi (0.65.1)
Installing React-jsiexecutor (0.65.1)
Installing React-jsinspector (0.65.1)
Installing React-perflogger (0.65.1)
Installing React-runtimeexecutor (0.65.1)
Installing ReactCommon (0.65.1)
Installing Yoga (1.14.0)
Installing YogaKit (1.18.1)
Installing boost-for-react-native (1.63.0)
Installing fmt (6.2.1)
Installing glog (0.3.5)
Installing libevent (2.1.12)
Generating Pods project
```
I don't see any Phrase SDK installing right ?

**Comment by christophemenager** [comment]
Closing this thread, as this is definitely not a problem, my bad !
