### ISSUE TITLE
Example without <Suspense /> ?

### ISSUE THREAD

**Issue by christophemenager** [phrase/react_native_sdk_example#3]
I have trouble using the SDK.

With your example it works, but in my real world application, I am stuck in the fallback render of the <Suspense /> component.

Can you explain a bit more why we need to add a Suspense component to make your sdk work ? Can this be avoided ? 

Edit : after digging a bit, I found that adding the `use(ChainedBackend)` creates the need for Suspense, I still don't know why

**Comment by DarkMinstrel** [comment]
Hi Christophe!
Phrase needs to load its caches from the local storage during the initialisation process (before rendering starts), and surely it's an asynchronous operation. That's why <Suspense /> is used and it works as a preloader.

**Comment by christophemenager** [comment]
Thanks for your answer @DarkMinstrel !

Actually my issue was not related to Suspense, but to the way I was initializing i18n. I forgot to remove the `resources` key from the init object. 

Maybe it can help others :  becareful while you migrate to using Phrase sdk with the `backend` key, not to forget to remove this `resources` key. (it's already taken care of with the backendFallback
