### ISSUE TITLE
Error when we run Jest test cases

### ISSUE THREAD

**Issue by mahipalsingh-syt** [phrase/react_native_sdk_example#5]
TypeError: _reactNativePhraseSdk.default is not a constructor

      35 | }
      36 |
    > 37 | const phrase = new Phrase(PHRASE_SECRET, PHRASE_DISTRIBUTION, "0.0.1", "i18next")
         |                ^
      38 |

**Comment by theSoenke** [comment]
Hi @mahipalsingh-syt, could you share how the import of the `Phrase` class is looking? The example app contains one example where a new `Phrase` object is created: https://github.com/phrase/react_native_sdk_example/blob/main/i18n.js#L5

**Comment by theSoenke** [comment]
Hi @mahipalsingh-syt, is this still an issue you're running into or can this be closed?
