### ISSUE TITLE
Bug in `requestTranslation` function

### ISSUE THREAD

**Issue by mkurczewski** [phrase/react_native_sdk_example#8]
Hi. I noticed a small (but meaningful) bug in the code of `react-native-phrase-sdk` library.

There's a function called `requestTranslation` in `phrase.js` file which is as following:

```TSX
async requestTranslation(localeCode) {
  this.updateFromApi(localeCode).then(
    //do nothing
  )
  return await this.loadFromCache(localeCode)
}
```

The issue is that this is not a way how promises are working in JavaScript. There are two different approaches mixed which leads to wrong results. The `loadFromCache` function is awaited for cache, but it doesn't wait for `updateFromApi` function to finish. In fact, they are fired at the same time, which leads to returning always the previously cached translations, rather than the newly fetched & cached one (by the `updateFromApi` function).

The resulting effect is that when user opens the app first time after a new translations OTA update was released, he still is going to see the old translations, until the app will be restarted again.

My workaround is to use own implementation of `requestTranslation` function by using `updateFromApi` and `loadFromCache` methods separately:

```TSX
const backendPhrase = resourcesToBackend(
  async (language, namespace, callback) => {
    try {
      const requestTranslation = async () => {
        await phraseInstance.updateFromApi(language)
        return phraseInstance.loadFromCache(language)
      }

      const remoteResources = await requestTranslation()
      callback(undefined, remoteResources)
    } catch {
      //
    }
  }
)
```

The above solution is practically the same way how this should be fixed in the original implementation. However, no repo is available publicly and I can't create a PR with the fix. Fortunately, the change is very simple and I hope it will be released soon 🤞  The copy & paste solution is to replace lines from 60-63 in `phrase.js` file with the following content:

```TSX
    async requestTranslation(localeCode) {
        await this.updateFromApi(localeCode)
        return await this.loadFromCache(localeCode)
    }
```

**Comment by theSoenke** [comment]
Hi @mkurczewski, thanks for the detailed report! The idea here was to run the update in the background to avoid blocking the app from start while translations are fetched. The updated translations should then only be displayed on the next start. This is similar how the SDKs on the other platforms work as well. But I think the documentation needs to a bit more clear here and provide some examples how to for example manually request a translation update and waiting for it to finish. I'll try to improve this

**Comment by theSoenke** [comment]
Completely agree `then` is not needed and I'll try to make sure it's no longer part of the next release. 

Your example totally looks like a proper solution to me. In most cases this should also be really fast only in cases where the translation release is large and the network connection slow this could cause problems
